

# ================== OBSOLETE ====================

vital_tags_sese = ["elbow gloves, fishnet thighhighs,detached collar, earrings, feet,  chocker, breasts, gloves,  heart-shaped pupils, limited palette, silver hair, breasts out, chain, clothing cutout, blush, nipple piercing, blindfolded, frilled dress, cleavage, cuffs, maid, alternate costume, maid bikini, maid headdress, blindfold, bed, leash, dildo, facing viewer,medium breasts,  gothic, hair between eyes, hair ribbon, handcuffs,fishnet legwear, yoisaki kanade, enmaided, waist apron, red rope, thighhighs, bdsm, garter straps, arms up, sleeveless dress, cat ears, animal ear fluff, ribbon-trimmed dress"]

vital_tags_mai = ["maimuro, bangs, black nails, bracelet, buttons, earrings, eyebrows hidden by hair, grey eyes, hair between eyes, hands up, hooded jacket, jacket, jewelry, long hair, looking at viewer, mismatched earrings, mole under eye, nail polish, parted lips, ring, ringed eyes, shirt, solo, turtleneck, upper body, white shirt"]

vital_tags_norm = ["two-tone hair, long sleeves, oversized clothes, medium hair, face focus, upper body, limited palette, looking at viewer, light smile"]

vital_tags2 = ["fishnet legwear", "chocker", "open clothes", "sleeveless", "thighhighs", "leg focus",
    "black dress", "gothic", "girl on top", "sex", "socks", "saliva", "clothed female nude male",
    "foot on head", "from below", "bdsm", "pantyshot", "light smile", "foreshortening", "indoors", "looking at viewer", "stepped on", "1boy", "hetero"]

start_tags_sese = ["best quality", "a clean painting of 1girl", "bdsm", "hatsune miku", "dildo gag", "fishnets", "yingyi", "explicit", "nsfw", "drolling", "sex toy", "tongue out", "masturbation", "pussy", "hetero", "slave", "enslaved", "sex toys", "condom", "fake dildo", "sex toys"]

vital_tags = ["oversized clothes, two-tone hair, petals,chromatic abbrevation, jewlry, limited palette"]
